/*
 * This file is generated by jOOQ.
*/
package de.quinscape.domainql.skat.domain.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "user_config", schema = "public", indexes = {
    @Index(name = "fki_config_user_user", columnList = "user_id ASC"),
    @Index(name = "pk_user_config", unique = true, columnList = "id ASC"),
    @Index(name = "uc_user_config_user_id", unique = true, columnList = "user_id ASC")
})
public class UserConfig implements Serializable {

    private static final long serialVersionUID = 1544862713;

    private String  id;
    private String  userId;
    private Boolean lockBidding;

    public UserConfig() {}

    public UserConfig(UserConfig value) {
        this.id = value.id;
        this.userId = value.userId;
        this.lockBidding = value.lockBidding;
    }

    public UserConfig(
        String  id,
        String  userId,
        Boolean lockBidding
    ) {
        this.id = id;
        this.userId = userId;
        this.lockBidding = lockBidding;
    }

    @Id
    @Column(name = "id", unique = true, nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Column(name = "user_id", unique = true, nullable = false, length = 36)
    @NotNull
    @Size(max = 36)
    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @Column(name = "lock_bidding")
    public Boolean getLockBidding() {
        return this.lockBidding;
    }

    public void setLockBidding(Boolean lockBidding) {
        this.lockBidding = lockBidding;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserConfig (");

        sb.append(id);
        sb.append(", ").append(userId);
        sb.append(", ").append(lockBidding);

        sb.append(")");
        return sb.toString();
    }
}
