sed -e 's/symbol:card-0"/symbol:kard-24"/'  \
    -e 's/symbol:card-1"/symbol:kard-25"/'  \
    -e 's/symbol:card-2"/symbol:kard-26"/'  \
    -e 's/symbol:card-3"/symbol:kard-27"/'  \
    -e 's/symbol:card-4"/symbol:kard-28"/'  \
    -e 's/symbol:card-5"/symbol:kard-29"/'  \
    -e 's/symbol:card-6"/symbol:kard-30"/'  \
    -e 's/symbol:card-7"/symbol:kard-31"/'  \
    -e 's/symbol:card-8"/symbol:kard-16"/'  \
    -e 's/symbol:card-9"/symbol:kard-17"/'  \
    -e 's/symbol:card-10"/symbol:kard-18"/' \
    -e 's/symbol:card-11"/symbol:kard-19"/' \
    -e 's/symbol:card-12"/symbol:kard-20"/' \
    -e 's/symbol:card-13"/symbol:kard-21"/' \
    -e 's/symbol:card-14"/symbol:kard-22"/' \
    -e 's/symbol:card-15"/symbol:kard-23"/' \
    -e 's/symbol:card-16"/symbol:kard-8"/'  \
    -e 's/symbol:card-17"/symbol:kard-9"/'  \
    -e 's/symbol:card-18"/symbol:kard-10"/' \
    -e 's/symbol:card-19"/symbol:kard-11"/' \
    -e 's/symbol:card-20"/symbol:kard-12"/' \
    -e 's/symbol:card-21"/symbol:kard-13"/' \
    -e 's/symbol:card-22"/symbol:kard-14"/' \
    -e 's/symbol:card-23"/symbol:kard-15"/'  \
    -e 's/symbol:card-24"/symbol:kard-0"/'  \
    -e 's/symbol:card-25"/symbol:kard-1"/'  \
    -e 's/symbol:card-26"/symbol:kard-2"/'  \
    -e 's/symbol:card-27"/symbol:kard-3"/'  \
    -e 's/symbol:card-28"/symbol:kard-4"/'  \
    -e 's/symbol:card-29"/symbol:kard-5"/'  \
    -e 's/symbol:card-30"/symbol:kard-6"/'  \
    -e 's/symbol:card-31"/symbol:kard-7"/'

