/*
 * This file is generated by jOOQ.
*/
package de.quinscape.domainql.skat.domain.tables;


import de.quinscape.domainql.skat.domain.Indexes;
import de.quinscape.domainql.skat.domain.Keys;
import de.quinscape.domainql.skat.domain.Public;
import de.quinscape.domainql.skat.domain.tables.records.AppLoginRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppLogin extends TableImpl<AppLoginRecord> {

    private static final long serialVersionUID = -733366079;

    /**
     * The reference instance of <code>public.app_login</code>
     */
    public static final AppLogin APP_LOGIN = new AppLogin();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppLoginRecord> getRecordType() {
        return AppLoginRecord.class;
    }

    /**
     * The column <code>public.app_login.username</code>.
     */
    public final TableField<AppLoginRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.app_login.series</code>.
     */
    public final TableField<AppLoginRecord, String> SERIES = createField("series", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.app_login.token</code>.
     */
    public final TableField<AppLoginRecord, String> TOKEN = createField("token", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.app_login.last_used</code>.
     */
    public final TableField<AppLoginRecord, Timestamp> LAST_USED = createField("last_used", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>public.app_login</code> table reference
     */
    public AppLogin() {
        this(DSL.name("app_login"), null);
    }

    /**
     * Create an aliased <code>public.app_login</code> table reference
     */
    public AppLogin(String alias) {
        this(DSL.name(alias), APP_LOGIN);
    }

    /**
     * Create an aliased <code>public.app_login</code> table reference
     */
    public AppLogin(Name alias) {
        this(alias, APP_LOGIN);
    }

    private AppLogin(Name alias, Table<AppLoginRecord> aliased) {
        this(alias, aliased, null);
    }

    private AppLogin(Name alias, Table<AppLoginRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PK_APP_LOGIN);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AppLoginRecord> getPrimaryKey() {
        return Keys.PK_APP_LOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AppLoginRecord>> getKeys() {
        return Arrays.<UniqueKey<AppLoginRecord>>asList(Keys.PK_APP_LOGIN);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppLogin as(String alias) {
        return new AppLogin(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppLogin as(Name alias) {
        return new AppLogin(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AppLogin rename(String name) {
        return new AppLogin(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AppLogin rename(Name name) {
        return new AppLogin(name, null);
    }
}
