/*
 * This file is generated by jOOQ.
*/
package de.quinscape.domainql.skat.domain;


import de.quinscape.domainql.skat.domain.tables.AppLogin;
import de.quinscape.domainql.skat.domain.tables.AppUser;
import de.quinscape.domainql.skat.domain.tables.UserConfig;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index PK_APP_LOGIN = Indexes0.PK_APP_LOGIN;
    public static final Index PK_APP_USER = Indexes0.PK_APP_USER;
    public static final Index UC_APP_USER_LOGIN = Indexes0.UC_APP_USER_LOGIN;
    public static final Index FKI_CONFIG_USER_USER = Indexes0.FKI_CONFIG_USER_USER;
    public static final Index PK_USER_CONFIG = Indexes0.PK_USER_CONFIG;
    public static final Index UC_USER_CONFIG_USER_ID = Indexes0.UC_USER_CONFIG_USER_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index PK_APP_LOGIN = Internal.createIndex("pk_app_login", AppLogin.APP_LOGIN, new OrderField[] { AppLogin.APP_LOGIN.SERIES }, true);
        public static Index PK_APP_USER = Internal.createIndex("pk_app_user", AppUser.APP_USER, new OrderField[] { AppUser.APP_USER.ID }, true);
        public static Index UC_APP_USER_LOGIN = Internal.createIndex("uc_app_user_login", AppUser.APP_USER, new OrderField[] { AppUser.APP_USER.LOGIN }, true);
        public static Index FKI_CONFIG_USER_USER = Internal.createIndex("fki_config_user_user", UserConfig.USER_CONFIG, new OrderField[] { UserConfig.USER_CONFIG.USER_ID }, false);
        public static Index PK_USER_CONFIG = Internal.createIndex("pk_user_config", UserConfig.USER_CONFIG, new OrderField[] { UserConfig.USER_CONFIG.ID }, true);
        public static Index UC_USER_CONFIG_USER_ID = Internal.createIndex("uc_user_config_user_id", UserConfig.USER_CONFIG, new OrderField[] { UserConfig.USER_CONFIG.USER_ID }, true);
    }
}
