/*
 * This file is generated by jOOQ.
*/
package de.quinscape.domainql.skat.domain;


import de.quinscape.domainql.skat.domain.tables.AppLogin;
import de.quinscape.domainql.skat.domain.tables.AppUser;
import de.quinscape.domainql.skat.domain.tables.UserConfig;
import de.quinscape.domainql.skat.domain.tables.records.AppLoginRecord;
import de.quinscape.domainql.skat.domain.tables.records.AppUserRecord;
import de.quinscape.domainql.skat.domain.tables.records.UserConfigRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AppLoginRecord> PK_APP_LOGIN = UniqueKeys0.PK_APP_LOGIN;
    public static final UniqueKey<AppUserRecord> PK_APP_USER = UniqueKeys0.PK_APP_USER;
    public static final UniqueKey<AppUserRecord> UC_APP_USER_LOGIN = UniqueKeys0.UC_APP_USER_LOGIN;
    public static final UniqueKey<UserConfigRecord> PK_USER_CONFIG = UniqueKeys0.PK_USER_CONFIG;
    public static final UniqueKey<UserConfigRecord> UC_USER_CONFIG_USER_ID = UniqueKeys0.UC_USER_CONFIG_USER_ID;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<UserConfigRecord, AppUserRecord> USER_CONFIG__FK_USER_CONFIG_USER = ForeignKeys0.USER_CONFIG__FK_USER_CONFIG_USER;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<AppLoginRecord> PK_APP_LOGIN = Internal.createUniqueKey(AppLogin.APP_LOGIN, "pk_app_login", AppLogin.APP_LOGIN.SERIES);
        public static final UniqueKey<AppUserRecord> PK_APP_USER = Internal.createUniqueKey(AppUser.APP_USER, "pk_app_user", AppUser.APP_USER.ID);
        public static final UniqueKey<AppUserRecord> UC_APP_USER_LOGIN = Internal.createUniqueKey(AppUser.APP_USER, "uc_app_user_login", AppUser.APP_USER.LOGIN);
        public static final UniqueKey<UserConfigRecord> PK_USER_CONFIG = Internal.createUniqueKey(UserConfig.USER_CONFIG, "pk_user_config", UserConfig.USER_CONFIG.ID);
        public static final UniqueKey<UserConfigRecord> UC_USER_CONFIG_USER_ID = Internal.createUniqueKey(UserConfig.USER_CONFIG, "uc_user_config_user_id", UserConfig.USER_CONFIG.USER_ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<UserConfigRecord, AppUserRecord> USER_CONFIG__FK_USER_CONFIG_USER = Internal.createForeignKey(
            Keys.PK_APP_USER, UserConfig.USER_CONFIG, "user_config__fk_user_config_user", UserConfig.USER_CONFIG.USER_ID);
    }
}
