/*
 * This file is generated by jOOQ.
*/
package de.quinscape.domainql.skat.domain;


import de.quinscape.domainql.skat.domain.tables.AppLogin;
import de.quinscape.domainql.skat.domain.tables.AppUser;
import de.quinscape.domainql.skat.domain.tables.UserConfig;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.app_login</code>.
     */
    public static final AppLogin APP_LOGIN = AppLogin.APP_LOGIN;

    /**
     * The table <code>public.app_user</code>.
     */
    public static final AppUser APP_USER = AppUser.APP_USER;

    /**
     * The table <code>public.user_config</code>.
     */
    public static final UserConfig USER_CONFIG = UserConfig.USER_CONFIG;
}
